{% set name = "neatnet" %}
{% set version = "0.0.1" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/neatnet-{{ version }}.tar.gz
  sha256: 266c420995d76ecbcf8838484fb75442e859bd7434ab8bf9184cda2bfd086a35

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
    - pip
  run:
    - python >={{ python_min }}
    - esda >=2.6.0
    - geopandas >=1.0.1
    - libpysal >=4.12.1
    - momepy >=0.9.0
    - networkx >=3.3
    - numpy >=1.26.4
    - pandas >=2.2.3
    - scipy >=1.14.1
    - shapely >=2.0.6

test:
  imports:
    - neatnet
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/uscuni/neatnet
  summary: Street geometry processing toolkit
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - martinfleis
    - jGaboardi
    - anastassiavybornova
